### ISSUE TITLE
Отображение

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-WotLK/ElvUI_MinimapButtons#3]
Как я понимаю слот под кнопку создается, но иконка туда не отправляется. Может уменьшить размер иконок чтобы помещалось в пределах миникарты?
![wowscrnshot_012417_163514](https://cloud.githubusercontent.com/assets/14907962/22249251/3cdb964c-e253-11e6-8327-c2b73ec8aa60.jpg)

**Comment by Bunny67** [comment]
Настройки этих кнопок, тут:
![wowscrnshot_012417_165536](https://cloud.githubusercontent.com/assets/5816685/22249907/fec105f6-e255-11e6-8f68-ecd94920dda0.jpg)

**Comment by Bunny67** [comment]
Баг как у тебя, у меня не получилось воспроизвести, если есть возможность залей все свои аддоны на какой нибудь файлообменник

**Comment by Sdw8** [comment]
[http://dropmefiles.com/raHWC](url)

**Comment by Bunny67** [comment]
С него не смог скачать :(

**Comment by Bunny67** [comment]
Хм, выключил AdBlock и скачал :)

**Comment by Bunny67** [comment]
Кнопки багаются из за Картографа, пока что решения не искал
